# Generated by Django 3.2.25 on 2025-03-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orginfo',
            options={'verbose_name': '机构信息', 'verbose_name_plural': '机构信息'},
        ),
        migrations.AlterField(
            model_name='orginfo',
            name='course_name',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
    ]
